Update backtests.yml

diff --git a/.github/workflows/backtests.yml b/.github/workflows/backtests.yml
--- a/.github/workflows/backtests.yml
+++ b/.github/workflows/backtests.yml
@@ -7,6 +7,53 @@ on:
       - 'NostalgiaForInfinityX7.py'
 
 jobs:
+
+  # Check Binance Proxys
+  Check-Binance-Proxy-Spot:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify Binance Spot Proxy
+        env:
+          PROXY: ${{ secrets.FREQTRADE_PROXY }}
+        run: |
+          HTTP_CODE=$(curl \
+            --proxy "$PROXY" \
+            -s \
+            -o /dev/null \
+            -w "%{http_code}" \
+            https://api.binance.com/api/v3/ping)
+
+          echo "HTTP response: $HTTP_CODE"
+
+          if [ "$HTTP_CODE" != "200" ]; then
+            echo "::error::Proxy test failed (HTTP $HTTP_CODE)"
+            exit 1
+          fi
+
+          echo "✅ Proxy works"
+  Check-Binance-Proxy-Futures:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify Binance Futures Proxy
+        env:
+          PROXY: ${{ secrets.FREQTRADE_PROXY2 }}
+        run: |
+          HTTP_CODE=$(curl \
+            --proxy "$PROXY" \
+            -s \
+            -o /dev/null \
+            -w "%{http_code}" \
+            https://api.binance.com/api/v3/ping)
+
+          echo "HTTP response: $HTTP_CODE"
+
+          if [ "$HTTP_CODE" != "200" ]; then
+            echo "::error::Proxy test failed (HTTP $HTTP_CODE)"
+            exit 1
+          fi
+
+          echo "✅ Proxy works"
+
   # Backtest Jobs
   Backtest-Kucoin-Spot:
     runs-on: ubuntu-latest
@@ -76,6 +123,7 @@ jobs:
           path: artifacts/
 
   Backtest-Binance-Spot:
+    needs: Check-Binance-Proxy-Spot
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -107,25 +155,6 @@ jobs:
           jq --arg proxy "$PROXY" \
             '.exchange.ccxt_config = { http_proxy: $proxy }' \
             configs/proxy-binance.json > tmp.json && mv tmp.json configs/proxy-binance.json
-      - name: Verify if the proxy works
-        env:
-          PROXY: ${{ secrets.FREQTRADE_PROXY }}
-        run: |
-          HTTP_CODE=$(curl \
-            --proxy "$PROXY" \
-            -s \
-            -o /dev/null \
-            -w "%{http_code}" \
-            https://api.binance.com/api/v3/ping)
-
-          echo "HTTP response: $HTTP_CODE"
-
-          if [ "$HTTP_CODE" != "200" ]; then
-            echo "::error::Proxy test failed (HTTP $HTTP_CODE)"
-            exit 1
-          fi
-
-          echo "✅ Proxy works"
   
       - name: Pull docker image
         run: |
@@ -170,6 +199,7 @@ jobs:
           path: artifacts/
 
   Backtest-Binance-Futures:
+    needs: Check-Binance-Proxy-Futures
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -201,26 +231,6 @@ jobs:
           jq --arg proxy "$PROXY" \
             '.exchange.ccxt_config = { http_proxy: $proxy }' \
             configs/proxy-binance.json > tmp.json && mv tmp.json configs/proxy-binance.json
-
-      - name: Verify if the proxy works
-        env:
-          PROXY: ${{ secrets.FREQTRADE_PROXY2 }}
-        run: |
-          HTTP_CODE=$(curl \
-            --proxy "$PROXY" \
-            -s \
-            -o /dev/null \
-            -w "%{http_code}" \
-            https://api.binance.com/api/v3/ping)
-
-          echo "HTTP response: $HTTP_CODE"
-
-          if [ "$HTTP_CODE" != "200" ]; then
-            echo "::error::Proxy test failed (HTTP $HTTP_CODE)"
-            exit 1
-          fi
-
-          echo "✅ Proxy works"
 
       - name: Pull docker image
         run: |
